#!/usr/bin/env node
// Render all skills from `skills/*.md` into per-tool files under `--target` repo.
// Zero dependencies — Node 18+.
//
// Usage:
//   node scripts/sync.mjs --target /path/to/consumer-repo
//   node scripts/sync.mjs --target /path/to/consumer-repo --dry-run

import { readFile, writeFile, readdir, mkdir, rm, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SKILLS_DIR = join(ROOT, "skills");
const TEMPLATES_DIR = join(ROOT, "templates");
const MANIFEST = JSON.parse(await readFile(join(ROOT, "manifest.json"), "utf8"));

const args = parseArgs(process.argv.slice(2));
if (!args.target) {
  console.error("Usage: sync.mjs --target <path-to-repo> [--dry-run]");
  process.exit(2);
}
const TARGET = resolve(args.target);
if (!existsSync(TARGET)) {
  console.error(`Target does not exist: ${TARGET}`);
  process.exit(2);
}

// ---- load skills ----------------------------------------------------------

const skillFiles = (await readdir(SKILLS_DIR)).filter((f) => f.endsWith(".md"));
const skills = await Promise.all(
  skillFiles.map(async (file) => {
    const raw = await readFile(join(SKILLS_DIR, file), "utf8");
    const { frontmatter, body } = parseFrontmatter(raw);
    const slug = file.replace(/\.md$/, "");
    if (!frontmatter.name) throw new Error(`${file}: missing 'name' in frontmatter`);
    if (!frontmatter.description) throw new Error(`${file}: missing 'description'`);
    return {
      slug,
      name: frontmatter.name,
      description: frontmatter.description,
      globs: Array.isArray(frontmatter.globs) ? frontmatter.globs : [],
      alwaysApply: frontmatter.alwaysApply === true,
      body: body.trim(),
      bodyWithoutH1: stripLeadingH1(body).trim(),
    };
  }),
);

skills.sort((a, b) => a.slug.localeCompare(b.slug));

// ---- load templates ------------------------------------------------------

async function loadTemplate(name) {
  return readFile(join(TEMPLATES_DIR, name), "utf8");
}

// ---- render outputs ------------------------------------------------------

const writes = []; // { path, content }
const oldGenPaths = new Set(); // for cleanup of stale per-skill files

for (const out of MANIFEST.outputs) {
  if (out.mode === "per-skill") {
    const tmpl = await loadTemplate(out.template);
    for (const skill of skills) {
      const path = join(TARGET, out.pathTemplate.replace("{slug}", skill.slug));
      const content = render(tmpl, skill);
      writes.push({ path, content });
    }
  } else if (out.mode === "combined") {
    const header = await loadTemplate(out.headerTemplate);
    const skillTmpl = await loadTemplate(out.skillTemplate);
    const path = join(TARGET, out.path);
    const sections = skills.map((s) => render(skillTmpl, s)).join("\n");
    const content = render(header, { /* header has no skill vars */ }) + sections;
    writes.push({ path, content });
  } else if (out.mode === "verbatim") {
    const src = join(ROOT, out.sourcePath);
    const path = join(TARGET, out.targetPath);
    let raw;
    try {
      raw = await readFile(src, "utf8");
    } catch {
      throw new Error(`verbatim source not found: ${out.sourcePath}`);
    }
    const isMarkdown = out.targetPath.endsWith(".md");
    const header = isMarkdown
      ? `<!-- AUTO-GENERATED by agent-skills sync from ${out.sourcePath}. Do not edit. -->\n\n`
      : `# AUTO-GENERATED by agent-skills sync from ${out.sourcePath}. Do not edit.\n\n`;
    writes.push({ path, content: header + raw });
  } else {
    throw new Error(`Unknown mode: ${out.mode}`);
  }
}

// ---- write (or print, if dry-run) ----------------------------------------

if (args["dry-run"]) {
  console.log(`# Dry run — ${writes.length} files would be written:\n`);
  for (const w of writes) {
    console.log(`  ${relative(TARGET, w.path)}  (${w.content.length} bytes)`);
  }
  process.exit(0);
}

let changed = 0;
for (const w of writes) {
  await mkdir(dirname(w.path), { recursive: true });
  let prev;
  try {
    prev = await readFile(w.path, "utf8");
  } catch {
    prev = null;
  }
  if (prev !== w.content) {
    await writeFile(w.path, w.content, "utf8");
    changed++;
    console.log(`wrote  ${relative(TARGET, w.path)}`);
  } else {
    console.log(`unchanged  ${relative(TARGET, w.path)}`);
  }
}

// Clean up per-skill files that no longer have a matching skill
for (const out of MANIFEST.outputs.filter((o) => o.mode === "per-skill")) {
  const pattern = out.pathTemplate;
  const dir = join(TARGET, dirname(pattern.replace("{slug}", "_")));
  if (!existsSync(dir)) continue;
  const expected = new Set(
    skills.map((s) => join(TARGET, pattern.replace("{slug}", s.slug))),
  );
  // Only clean files that look generated (header comment) — never delete
  // user files that happen to match the path scheme.
  for await (const present of walkFiles(dir)) {
    if (expected.has(present)) continue;
    if (!present.endsWith(".md") && !present.endsWith(".mdc")) continue;
    const head = await safeRead(present, 200);
    if (head && head.includes("AUTO-GENERATED by agent-skills sync")) {
      await rm(present);
      console.log(`removed stale  ${relative(TARGET, present)}`);
      changed++;
    }
  }
}

console.log(`\nDone. ${changed} files changed.`);

// ---- helpers -------------------------------------------------------------

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--target") out.target = argv[++i];
    else if (a === "--dry-run") out["dry-run"] = true;
    else if (a.startsWith("--")) out[a.slice(2)] = true;
  }
  return out;
}

function parseFrontmatter(raw) {
  if (!raw.startsWith("---")) return { frontmatter: {}, body: raw };
  const end = raw.indexOf("\n---", 3);
  if (end === -1) return { frontmatter: {}, body: raw };
  const yamlText = raw.slice(3, end).replace(/^\n/, "");
  const body = raw.slice(end + 4).replace(/^\n/, "");
  return { frontmatter: parseYaml(yamlText), body };
}

// Tiny YAML subset: top-level scalars, multi-line strings via quoting,
// and `key:` followed by `  - item` lines for arrays. Booleans true/false.
function parseYaml(text) {
  const out = {};
  const lines = text.split("\n");
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (!line.trim() || line.trimStart().startsWith("#")) {
      i++;
      continue;
    }
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$/);
    if (!m) {
      i++;
      continue;
    }
    const key = m[1];
    const rest = m[2];
    if (rest === "" || rest === "|") {
      // expect indented list or block
      const list = [];
      i++;
      while (i < lines.length && /^\s*-\s+/.test(lines[i])) {
        list.push(coerce(lines[i].replace(/^\s*-\s+/, "").trim()));
        i++;
      }
      if (list.length) {
        out[key] = list;
      } else {
        out[key] = "";
      }
      continue;
    }
    out[key] = coerce(rest.trim());
    i++;
  }
  return out;
}

function coerce(v) {
  if (v === "true") return true;
  if (v === "false") return false;
  if (v === "null") return null;
  if (/^-?\d+$/.test(v)) return Number(v);
  if (
    (v.startsWith('"') && v.endsWith('"')) ||
    (v.startsWith("'") && v.endsWith("'"))
  ) {
    return v.slice(1, -1);
  }
  return v;
}

function stripLeadingH1(body) {
  // Drop the first `# Heading` line if present, plus a single trailing newline.
  return body.replace(/^\s*#\s+[^\n]+\n+/, "");
}

function render(tmpl, vars) {
  return tmpl.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    if (key === "globsJson") return JSON.stringify(vars.globs ?? []);
    if (key === "globsCommaList") return (vars.globs ?? []).join(", ");
    if (key in vars) {
      const v = vars[key];
      if (typeof v === "boolean") return String(v);
      if (Array.isArray(v)) return v.join(", ");
      return v ?? "";
    }
    return "";
  });
}

async function* walkFiles(dir) {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) {
      yield* walkFiles(p);
    } else {
      yield p;
    }
  }
}

async function safeRead(path, bytes) {
  try {
    const buf = await readFile(path);
    return buf.subarray(0, bytes).toString("utf8");
  } catch {
    return null;
  }
}
